# Generated by Django 5.1.7 on 2025-04-19 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('create_data', models.DateTimeField(unique_for_date=models.CharField(max_length=255))),
                ('opening_after_date', models.DateTimeField()),
                ('public_access', models.BooleanField(default=False)),
                ('emergency_access', models.BooleanField(default=False)),
                ('ea_time', models.IntegerField(default=0)),
                ('ea_separation', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_data'],
            },
        ),
    ]
