# Generated by Django 5.1.7 on 2025-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_capsule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsules',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
