# Generated by Django 5.1.7 on 2025-05-15 16:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsulesModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('date_open', models.DateTimeField()),
                ('content_rating_ai', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('content_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('private', models.BooleanField(default=True)),
                ('share_mode', models.BooleanField(default=False)),
                ('share_link', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('share_password', models.CharField(blank=True, max_length=255, null=True)),
                ('text_bd', models.TextField(blank=True, null=True)),
                ('emergency_access', models.BooleanField(default=False)),
                ('ea_after_open', models.BooleanField(default=False)),
                ('ea_time_separation', models.JSONField(default=list)),
                ('count_opening', models.IntegerField(default=0)),
                ('count_change', models.JSONField(default=list)),
                ('opening_days_mode', models.BooleanField(default=False)),
                ('day_week_odm', models.CharField(blank=True, max_length=30, null=True)),
                ('num_week_odm', models.IntegerField(blank=True, default=0, null=True)),
                ('time_odm_start', models.TimeField(blank=True, null=True)),
                ('time_odm_end', models.TimeField(blank=True, null=True)),
                ('required_access_log', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsulesAPI', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='AccessLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='')),
                ('access_assessment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='time_capsule_api.capsulesmodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
